services:
  react:
    restart: always
    container_name: ${PROJECT_NAME}_react
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}"
    volumes: 
      - .:/app/
    working_dir: /app
    stdin_open: true
    tty: true
    command: ["npm", "run", "dev"]